# Generated by Django 4.1.3 on 2022-12-20 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Talaba_qushish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Talaba_ismi",
                    models.CharField(default="Nomalum", max_length=50, unique=True),
                ),
                (
                    "telfon_raqam",
                    models.DecimalField(decimal_places=0, max_digits=78, null=True),
                ),
                (
                    "OTM",
                    models.CharField(
                        choices=[("OTM example", "OTM example")],
                        default="None",
                        max_length=100,
                    ),
                ),
                (
                    "talabalik_turi",
                    models.CharField(
                        choices=[
                            ("Barchasi", "Barchasi"),
                            ("Bakalavr", "Bakalavr"),
                            ("Magistr", "Magistr"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                (
                    "Kontrakt_summa",
                    models.DecimalField(decimal_places=0, max_digits=78, null=True),
                ),
                (
                    "Ajratilgan_summa",
                    models.DecimalField(decimal_places=False, default=0, max_digits=78),
                ),
                (
                    "sana",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            12,
                            20,
                            15,
                            10,
                            26,
                            855542,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("foizda", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Homiy_qushish_talabaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homiy_tanla", models.CharField(default="None", max_length=200)),
                (
                    "qancha_summa",
                    models.DecimalField(decimal_places=0, max_digits=78, null=True),
                ),
                (
                    "Talaba_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talaba_homiysi",
                        to="talaba.talaba_qushish",
                    ),
                ),
            ],
        ),
    ]
