# Generated by Django 4.1.3 on 2022-12-20 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 20, 15, 10, 49, 47793, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
