# Generated by Django 4.1.3 on 2022-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talaba_qushish",
            name="Ajratilgan_summa",
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name="talaba_qushish",
            name="Kontrakt_summa",
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name="talaba_qushish",
            name="OTM",
            field=models.CharField(
                choices=[("OTM example", "OTM example")], default="None", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="talaba_qushish",
            name="talabalik_turi",
            field=models.CharField(
                choices=[
                    ("Barchasi", "Barchasi"),
                    ("Bakalavr", "Bakalavr"),
                    ("Magistr", "Magistr"),
                ],
                default="None",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="talaba_qushish",
            name="telfon_raqam",
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="Talaba_ismi",
            field=models.CharField(default="Nomalum", max_length=50, unique=True),
        ),
    ]
