# Generated by Django 4.0.4 on 2022-12-16 22:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba_qushish',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 22, 3, 3, 665875, tzinfo=utc)),
        ),
    ]
