# Generated by Django 4.1.3 on 2022-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0002_talaba_qushish_ajratilgan_summa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
