# Generated by Django 4.0.4 on 2022-12-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0001_initial'),
        ('talaba', '0003_alter_talaba_qushish_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiy_qushish_talabaga',
            name='homiy_tanla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homiy.homiyarizasi'),
        ),
    ]
