# Generated by Django 4.1.3 on 2022-12-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0004_alter_talaba_qushish_sana"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homiy_qushish_talabaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homiy_tanla",
                    models.CharField(choices=[], default="None", max_length=200),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 12, 17, 13, 5, 83186, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
