# Generated by Django 4.1.3 on 2022-12-12 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homiy", "0001_initial"),
        ("talaba", "0005_homiy_qushish_talabaga_alter_talaba_qushish_sana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="homiy_tanla",
            field=models.ForeignKey(
                max_length=78,
                on_delete=django.db.models.deletion.CASCADE,
                to="homiy.homiyarizasi",
            ),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 12, 18, 10, 19, 474743, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
