# Generated by Django 4.1.3 on 2022-12-13 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homiy", "0001_initial"),
        ("talaba", "0009_alter_homiy_qushish_talabaga_homiy_tanla_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="homiy_tanla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="homiy.homiyarizasi",
                verbose_name="Homiy_tanala",
            ),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 13, 17, 33, 25, 759717, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
