# Generated by Django 4.1.3 on 2022-12-18 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homiy", "0003_homiyarizasi_ariza_holati"),
        ("talaba", "0010_alter_talaba_qushish_sana"),
    ]

    operations = [
        migrations.AddField(
            model_name="talaba_qushish",
            name="homiy_uz",
            field=models.ForeignKey(
                limit_choices_to=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homiy.homiyarizasi",
            ),
        ),
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="Talaba_Id",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 18, 7, 40, 9, 35068, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
