# Generated by Django 4.1.3 on 2022-12-18 08:21

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0011_talaba_qushish_homiy_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talaba_qushish",
            name="homiy_uz",
        ),
        migrations.AddField(
            model_name="talaba_qushish",
            name="homiy",
            field=multiselectfield.db.fields.MultiSelectField(
                default="None", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 18, 8, 21, 25, 127286, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
