# Generated by Django 4.1.3 on 2022-12-18 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0012_remove_talaba_qushish_homiy_uz_talaba_qushish_homiy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talaba_qushish",
            name="homiy",
        ),
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="Talaba_Id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="talaba.talaba_qushish",
            ),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 18, 8, 30, 4, 115352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
