# Generated by Django 4.1.3 on 2022-12-18 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0013_remove_talaba_qushish_homiy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="Talaba_Id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talaba_homiysi",
                to="talaba.talaba_qushish",
            ),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="Ajratilgan_summa",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 18, 11, 15, 29, 452413, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
