# Generated by Django 4.1.3 on 2022-12-13 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talaba", "0014_alter_talaba_qushish_sana"),
    ]

    operations = [
        migrations.AddField(
            model_name="homiy_qushish_talabaga",
            name="Talaba_Ismi",
            field=models.CharField(default="None", max_length=200),
        ),
        migrations.AddField(
            model_name="homiy_qushish_talabaga",
            name="qancha_summa",
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name="homiy_qushish_talabaga",
            name="homiy_tanla",
            field=models.CharField(default="None", max_length=200),
        ),
        migrations.AlterField(
            model_name="talaba_qushish",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 13, 20, 0, 40, 363586, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
