# Generated by Django 4.1.3 on 2022-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_app", "0007_alter_homiyarizasi_balans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homiyqushish_talabaga",
            name="homiy",
        ),
        migrations.DeleteModel(
            name="LibUser",
        ),
        migrations.DeleteModel(
            name="TalabaQushish",
        ),
        migrations.RemoveField(
            model_name="homiyarizasi",
            name="Shaxs_turi",
        ),
        migrations.RemoveField(
            model_name="homiyarizasi",
            name="tashkilot_nomi_yuridik_uchun",
        ),
        migrations.AlterField(
            model_name="homiyarizasi",
            name="ariza_holati",
            field=models.CharField(
                choices=[
                    ("Tasdiqlanmagan", "Tasdiqlanmagan"),
                    ("Tasdiqlandi", "Tasdiqlandi"),
                ],
                default="Yangi",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="HomiyQushish_Talabaga",
        ),
    ]
