# Generated by Django 4.1.3 on 2022-12-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homiy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homiyarizasi",
            name="ariza_holati",
        ),
    ]
