# Generated by Django 4.1.3 on 2022-12-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homiy", "0002_remove_homiyarizasi_ariza_holati"),
    ]

    operations = [
        migrations.AddField(
            model_name="homiyarizasi",
            name="ariza_holati",
            field=models.CharField(
                choices=[
                    ("Yangi", "Yangi"),
                    ("Moderatsiyada", " Moderatsiyada"),
                    ("Tasdiqlandi", "Tasdiqlandi"),
                    ("Bekor qilingan", "Bekor qilingan"),
                ],
                default="Yangi",
                max_length=30,
            ),
        ),
    ]
